### ISSUE TITLE
Clear button next to search bar

### ISSUE THREAD

**Issue by JinayJain** [JinayJain/gpt-anywhere#10]

**Comment by ANG020323** [comment]
buddy,i don't see this function,and can't see the other functions add, i really love your project,the best i have ever see!!!!!!!!

**Comment by ANG020323** [comment]
and can i recommand to remove the app icon/offer a setting to just show it on the menu bar

**Comment by JinayJain** [comment]
> buddy,i don't see this function,and can't see the other functions add, i really love your project,the best i have ever see!!!!!!!!

The features in the issues tab are the ones I have planned for the future, so they're not implemented yet.

> and can i recommand to remove the app icon/offer a setting to just show it on the menu bar

> Two issues encountered: Latex is prone to errors when outputting formulas, and when using "clear" on MacOS, a transparent box appears, which affects the appearance.

Could you make new GitHub issues for these problems you found? @ANG-crypto
