### ISSUE TITLE
Show contents all at once

### ISSUE THREAD

**Issue by JerryJohnsonLee** [JinayJain/gpt-anywhere#13]
Is it possible to show contents all at once instead of character by character? (I think it should be because the openai API responses with the full message all at once)

**Comment by JinayJain** [comment]
The responses are shown as fast as the API is sending them to your computer, so all at once would take as much time as it takes to output the last word in the chunk-by-chunk version.

**Comment by JerryJohnsonLee** [comment]
Okay I see. Thanks for the explanation!

**Comment by JinayJain** [comment]
Of course! I'm just happy to see it's useful enough for you to give feedback :)
