### ISSUE TITLE
How do I install this on Windows?

### ISSUE THREAD

**Issue by jasonwilmot** [JinayJain/gpt-anywhere#14]
I might be missing something, but I don't see a exe or msi file anywhere?

**Comment by CSymes** [comment]
There is an `msi` build at the bottom of the list of assets on the release
e.g. for v0.0.1 - https://github.com/JinayJain/gpt-anywhere/releases/download/app-v0.0.1/GPT.Anywhere_0.0.1_x64_en-US.msi
