### ISSUE TITLE
Add an Model option and let users to choose GPT-4 or GPT-3.5

### ISSUE THREAD

**Issue by baibanbao** [JinayJain/gpt-anywhere#17]
Very simple and clear app, but it would be better if we can choose to use which model.

**Comment by JinayJain** [comment]
Hey @baibanbao , I've finally added support for switching between GPT 3.5 and GPT 4 (turbo) through a dropdown. The new version should be available [here](https://github.com/JinayJain/gpt-anywhere/releases/tag/app-v0.0.2).
