### ISSUE TITLE
Add ability to continue the chat

### ISSUE THREAD

**Issue by JinayJain** [JinayJain/gpt-anywhere#4]
Augment the interface to make it more ChatGPT like

**Comment by JerryJohnsonLee** [comment]
Thanks for developing this app and allowing continuous chat will be very helpful! I would imagine every time I press ctrl+shift+/ it will be a new chat thread with a fresh input box (right now there is text from last interaction that I need to delete manually), and if I do not press ctrl+shift+/ it would be considered in the same chat thread

**Comment by JinayJain** [comment]
I really appreciate your feedback @JerryJohnsonLee, I'm trying to figure out the best UX for these more complex features but I might go with your suggestion.
